Update setup.yml

diff --git a/.github/workflows/setup.yml b/.github/workflows/setup.yml
--- a/.github/workflows/setup.yml
+++ b/.github/workflows/setup.yml
@@ -8,7 +8,7 @@ on:
 
 env:
   TARGET_REPO: technical-director-acmvit/cli-top-website       # Original target repository
-  FORK_REPO: theg1239/cli-top-website                        # Your forked repository
+  FORK_REPO: theg1239/cli-top-website                          # Your forked repository
   VERSION_DIR_PREFIX: v
 
 jobs:
@@ -39,17 +39,20 @@ jobs:
           mkdir -p build/linux
           go build -o build/linux/cli-top .
 
-      - name: Upload Linux Binary
-        uses: actions/upload-artifact@v3
-        with:
-          name: cli-top-linux
-          path: ./build/linux/cli-top
-
       - name: Extract Version
         id: extract_version
         run: |
           VERSION=$(grep 'var Version string =' ./debug/debug.go | awk -F '"' '{print $2}')
           echo "version=${VERSION}" >> $GITHUB_OUTPUT
+
+      - name: Zip Linux Binary
+        run: zip cli-top-linux_v${{ steps.extract_version.outputs.version }}.zip build/linux/cli-top
+
+      - name: Upload Linux Binary
+        uses: actions/upload-artifact@v3
+        with:
+          name: cli-top-linux
+          path: cli-top-linux_v${{ steps.extract_version.outputs.version }}.zip
 
   build-windows:
     name: Build Windows Executable and Installer
@@ -88,7 +91,6 @@ jobs:
         id: extract_version
         shell: pwsh
         run: |
-          # Read the specific line containing the version
           $line = Get-Content -Path './debug/debug.go' | Select-String -Pattern 'var Version string ='
           if ($line -match 'var Version string = "(.*)"') {
               $version = $matches[1]
@@ -101,7 +103,7 @@ jobs:
 
       - name: Create Inno Setup Script
         run: |
-          $installerScript = @'
+          $installerScript = @"
           [Setup]
           AppName=CLI-TOP
           AppVersion=${{ steps.extract_version.outputs.version }}
@@ -178,9 +180,8 @@ jobs:
                      mbInformation, MB_OK);
             end;
           end;
-          '@
+"@
 
-          # Ensure no BOM is added by using UTF8NoBOM encoding
           Set-Content -Path installer.iss -Value $installerScript -Encoding UTF8NoBOM
 
       - name: Show Inno Setup Script (Debugging)
@@ -203,17 +204,22 @@ jobs:
           }
           Write-Host "Installer file exists: ./Output/cli-top-installer-${{ steps.extract_version.outputs.version }}.exe"
 
+      - name: Zip Windows Binary
+        shell: pwsh
+        run: Compress-Archive -Path 'build/windows/cli-top.exe' -DestinationPath "cli-top-windows_v${{ steps.extract_version.outputs.version }}.zip"
+
       - name: Upload Windows Executable
         uses: actions/upload-artifact@v3
         with:
           name: cli-top-windows
-          path: ./build/windows/cli-top.exe
+          path: cli-top-windows_v${{ steps.extract_version.outputs.version }}.zip
 
-      - name: Upload Windows Installer
-        uses: actions/upload-artifact@v3
-        with:
-          name: cli-top-windows-installer
-          path: ./Output/cli-top-installer-${{ steps.extract_version.outputs.version }}.exe
+      # If you also want to upload the installer, uncomment below
+      # - name: Upload Windows Installer
+      #   uses: actions/upload-artifact@v3
+      #   with:
+      #     name: cli-top-windows-installer
+      #     path: ./Output/cli-top-installer-${{ steps.extract_version.outputs.version }}.exe
 
   build-macos:
     name: Build MacOS Binary
@@ -241,11 +247,20 @@ jobs:
           GOOS=darwin GOARCH=amd64 go build -o build/macos/cli-top .
           chmod +x build/macos/cli-top
 
+      - name: Extract Version
+        id: extract_version
+        run: |
+          VERSION=$(grep 'var Version string =' ./debug/debug.go | awk -F '"' '{print $2}')
+          echo "version=${VERSION}" >> $GITHUB_OUTPUT
+
+      - name: Zip MacOS Binary
+        run: zip cli-top-macos_v${{ steps.extract_version.outputs.version }}.zip build/macos/cli-top
+
       - name: Upload MacOS Binary
         uses: actions/upload-artifact@v3
         with:
           name: cli-top-macos
-          path: ./build/macos/cli-top
+          path: cli-top-macos_v${{ steps.extract_version.outputs.version }}.zip
 
   build-android:
     name: Build Android Binary
@@ -273,99 +288,141 @@ jobs:
           GOOS=linux GOARCH=arm64 go build -o build/android/cli-top .
           chmod +x build/android/cli-top
 
+      - name: Extract Version
+        id: extract_version
+        run: |
+          VERSION=$(grep 'var Version string =' ./debug/debug.go | awk -F '"' '{print $2}')
+          echo "version=${VERSION}" >> $GITHUB_OUTPUT
+
+      - name: Zip Android Binary
+        run: zip cli-top-android_v${{ steps.extract_version.outputs.version }}.zip build/android/cli-top
+
       - name: Upload Android Binary
         uses: actions/upload-artifact@v3
         with:
           name: cli-top-android
-          path: ./build/android/cli-top
+          path: cli-top-android_v${{ steps.extract_version.outputs.version }}.zip
 
-	deploy:
-	  name: Deploy Binaries
-	  runs-on: ubuntu-latest
-	  needs: [build-linux, build-windows, build-macos, build-android]
-	  steps:
-	    - name: Checkout Fork Repository
-	      uses: actions/checkout@v3
-	      with:
-	        repository: ${{ env.FORK_REPO }}
-	        token: ${{ secrets.FORK_PAT }}
-	        path: target-repo
-	
-	    - name: Debug Repository Directory
-	      run: |
-	        echo "Contents of the target-repo directory:"
-	        ls -la target-repo
-	        if [ ! -d "target-repo/.git" ]; then
-	          echo "No Git repository detected in target-repo. Initializing..."
-	          cd target-repo
-	          git init
-	          git remote add origin https://github.com/${{ env.FORK_REPO }}.git
-	          git fetch origin
-	          git checkout -b main || git checkout -b default_branch
-	        fi
-	
-	    - name: Verify Git Configuration
-	      run: |
-	        cd target-repo
-	        git remote -v
-	        git branch
-	
-	    - name: Extract Version from Build
-	      id: extract_version
-	      run: |
-	        echo "version=${{ needs.build-linux.outputs.version }}" >> $GITHUB_OUTPUT
-	
-	    - name: Create Version Directory
-	      run: |
-	        VERSION_DIR="${{ env.VERSION_DIR_PREFIX }}${{ steps.extract_version.outputs.version }}"
-	        mkdir -p "target-repo/${VERSION_DIR}/linux"
-	        mkdir -p "target-repo/${VERSION_DIR}/windows"
-	        mkdir -p "target-repo/${VERSION_DIR}/macos"
-	        mkdir -p "target-repo/${VERSION_DIR}/android"
-	
-	    - name: Download Linux Binary
-	      uses: actions/download-artifact@v3
-	      with:
-	        name: cli-top-linux
-	        path: ./linux
-	
-	    - name: Move Artifacts to Fork Repository
-	      run: |
-	        VERSION_DIR="${{ env.VERSION_DIR_PREFIX }}${{ steps.extract_version.outputs.version }}"
-	        mv linux/cli-top "target-repo/${VERSION_DIR}/linux/"
-	    
-	    - name: Update latest.json
-	      run: |
-	        cd target-repo
-	        if [ -f "latest.json" ]; then
-	          jq --arg v "${{ steps.extract_version.outputs.version }}" '.version = $v' latest.json > tmp.json && mv tmp.json latest.json
-	        else
-	          echo "latest.json not found!"
-	          exit 1
-	        fi
-	
-	    - name: Define Branch Name
-	      id: define_branch
-	      run: echo "branch=add-binaries-v${{ steps.extract_version.outputs.version }}-${{ github.run_id }}" >> $GITHUB_OUTPUT
-	
-	    - name: Debug Branch Name
-	      run: echo "Generated branch name: ${{ steps.define_branch.outputs.branch }}"
-	
-	    - name: Commit and Push Changes to Fork
-	      run: |
-	        cd target-repo
-	        git config user.name "github-actions[bot]"
-	        git config user.email "github-actions[bot]@users.noreply.github.com"
-	        git checkout -b ${{ steps.define_branch.outputs.branch }}
-	        git add .
-	        git commit -m "Add binaries and update latest.json for version v${{ steps.extract_version.outputs.version }}" || echo "No changes to commit"
-	        git push origin ${{ steps.define_branch.outputs.branch }}
-	
-	    - name: Create Pull Request from Fork to Target
-	      uses: peter-evans/create-pull-request@v7
-	      with:
-	        token: ${{ secrets.FORK_PAT }}
-	        branch: ${{ steps.define_branch.outputs.branch }}
-	        commit-message: "Add binaries and update latest.json for version v${{ steps.extract_version.outputs.version }}"
-	        title: "Add binaries and update latest.json for version v${{ steps.extract_version.outputs.version }}"
-	        body: "This PR adds the binaries, Windows installer, and updates the latest.json file for version v${{ steps.extract_version.outputs.version }}."
+  deploy:
+    name: Deploy Binaries
+    runs-on: ubuntu-latest
+    needs: [build-linux, build-windows, build-macos, build-android]
+    steps:
+      - name: Checkout Fork Repository
+        uses: actions/checkout@v3
+        with:
+          repository: ${{ env.FORK_REPO }}
+          token: ${{ secrets.FORK_PAT }}
+          path: target-repo
+
+      - name: Debug Repository Directory
+        run: |
+          echo "Contents of the target-repo directory:"
+          ls -la target-repo
+          if [ ! -d "target-repo/.git" ]; then
+            echo "No Git repository detected in target-repo. Initializing..."
+            cd target-repo
+            git init
+            git remote add origin https://github.com/${{ env.FORK_REPO }}.git
+            git fetch origin
+            git checkout -b main || git checkout -b default_branch
+          fi
+
+      - name: Verify Git Configuration
+        run: |
+          cd target-repo
+          git remote -v
+          git branch
+
+      - name: Extract Version from Build
+        id: extract_version
+        run: |
+          echo "version=${{ needs.build-linux.outputs.version }}" >> $GITHUB_OUTPUT
+
+      - name: Create Version Directory
+        run: |
+          VERSION_DIR="${{ env.VERSION_DIR_PREFIX }}${{ steps.extract_version.outputs.version }}"
+          mkdir -p "target-repo/${VERSION_DIR}"
+
+      - name: Download Linux Artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: cli-top-linux
+          path: ./artifacts
+
+      - name: Download Windows Artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: cli-top-windows
+          path: ./artifacts
+
+      - name: Download MacOS Artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: cli-top-macos
+          path: ./artifacts
+
+      - name: Download Android Artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: cli-top-android
+          path: ./artifacts
+
+      - name: Move Artifacts to Fork Repository
+        run: |
+          VERSION_DIR="${{ env.VERSION_DIR_PREFIX }}${{ steps.extract_version.outputs.version }}"
+          mv artifacts/cli-top-linux_v${{ steps.extract_version.outputs.version }}.zip "target-repo/${VERSION_DIR}/"
+          mv artifacts/cli-top-windows_v${{ steps.extract_version.outputs.version }}.zip "target-repo/${VERSION_DIR}/"
+          mv artifacts/cli-top-macos_v${{ steps.extract_version.outputs.version }}.zip "target-repo/${VERSION_DIR}/"
+          mv artifacts/cli-top-android_v${{ steps.extract_version.outputs.version }}.zip "target-repo/${VERSION_DIR}/"
+
+      - name: Update latest.json
+        run: |
+          cd target-repo
+          if [ -f "latest.json" ]; then
+            jq --arg v "${{ steps.extract_version.outputs.version }}" '.version = $v' latest.json > tmp.json && mv tmp.json latest.json
+          else
+            echo "latest.json not found!"
+            exit 1
+          fi
+
+      - name: Define Branch Name
+        id: define_branch
+        run: echo "branch=add-binaries-v${{ steps.extract_version.outputs.version }}-${{ github.run_id }}" >> $GITHUB_OUTPUT
+
+      - name: Debug Branch Name
+        run: echo "Generated branch name: ${{ steps.define_branch.outputs.branch }}"
+
+      - name: Commit and Push Changes to Fork
+        run: |
+          cd target-repo
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+          git checkout -b ${{ steps.define_branch.outputs.branch }}
+          git add .
+          git commit -m "feat:v${{ steps.extract_version.outputs.version }} release" || echo "No changes to commit"
+          git push origin ${{ steps.define_branch.outputs.branch }}
+
+      - name: Create Pull Request from Fork to Target
+        uses: peter-evans/create-pull-request@v7
+        with:
+          token: ${{ secrets.FORK_PAT }}
+          branch: ${{ steps.define_branch.outputs.branch }}
+          commit-message: "feat:v${{ steps.extract_version.outputs.version }} release"
+          title: "feat:v${{ steps.extract_version.outputs.version }} release"
+          body: |
+            This PR adds the binaries and updates the latest.json file for version v${{ steps.extract_version.outputs.version }}.
+
+            cli-top-android_v${{ steps.extract_version.outputs.version }}.zip
+            feat:v${{ steps.extract_version.outputs.version }} release
+            last month
+
+            cli-top-linux_v${{ steps.extract_version.outputs.version }}.zip
+            feat:v${{ steps.extract_version.outputs.version }} release
+            last month
+
+            cli-top-macos_v${{ steps.extract_version.outputs.version }}.zip
+            feat:v${{ steps.extract_version.outputs.version }} release
+            last month
+
+            cli-top-windows_v${{ steps.extract_version.outputs.version }}.zip
